"""Explicit camera control for BEHAVIOR-TextWorld: the policy chooses where to look.

WHY THIS EXISTS, and it is not "because ALFWorld has viewpoints". ALFWorld's text agent
(BUTLER::BRAIN) emits nine high-level commands and **not one camera or motion
primitive**; MoveAhead/RotateLeft/LookUp/LookDown are generated by a separate
controller (BUTLER::BODY) running A* over a pre-built map of receptacle viewpoints. The
brain never chooses a viewpoint, and their own §3.3 concedes that pre-built map is "a
strong prior assumption". Putting the camera in the *policy's* action space is the
thing that architecture avoids. See
`code-doc/human-plan/0813 - 2.5D viewpoint layer & what separates this from ALFWorld.md`.

The other reason is empirical: the cheap observability levers are exhausted. Room
scoping hides almost nothing (87.7% of solvable activities are single-room), and
object-level gating measured as a flat null against a prompted frontier model
(McNemar p=1.0 both goal formats). Both told the policy the rule and let it follow one.
Deciding *where to look next* cannot be followed from a stated rule.

WHAT IS REAL HERE. Coordinates come from `layout.py`, which is explicit about whether
they were sampled by BEHAVIOR or generated by us. This module never reports a distance
in metres to the policy when the layout is generated -- see `_describe`. What it does
report either way is *relational and ordinal*: what is in view, roughly where in view,
and whether something is nearer than something else. Those hold under a generated
layout because they are properties of the layout, not claims about a house.

WHAT THIS DOES NOT DO. It does not replace `go_to`. Swapping oracle navigation for A*
over these primitives would dissolve the control oracle that the project deliberately
keeps (CLAUDE.md: the double oracle "isolates symbolic planning as the only measured
variable"), inflate every episode roughly tenfold in turns, and mostly measure
navigation. Instead `go_to` stays, gated on having *seen* the target -- discovery
becomes real work, navigation stays free. That is the smallest change that makes
looking matter.
"""
from __future__ import annotations

import math
from dataclasses import dataclass, field

# Matches `semantic_tools.FOV_HALF_ANGLE_RAD` / `FOV_RANGE_M` so the symbolic and
# geometric backends gate visibility the same way. One approximation to defend, not two.
FOV_HALF_ANGLE_RAD = math.radians(60.0)
FOV_RANGE_M = 8.0

# Vertical half-angle. Narrower than horizontal, as real cameras are.
FOV_HALF_PITCH_RAD = math.radians(35.0)

# 90 degrees, matching ALFRED's RotateLeft/Right. Measured against 45 and 120 on
# 20 activities: coverage was IDENTICAL (16/20 complete) at every setting, while
# median search cost fell 52 -> 28 -> 18 steps. 45 was pure waste against a
# 120-degree cone; 120 would leave zero overlap, so an object on the seam could be
# missed. 90 keeps 30 degrees of overlap for 4 steps a circle.
TURN_STEP_RAD = math.radians(90.0)
MOVE_STEP_M = 0.5
PITCH_STEP_RAD = math.radians(30.0)
PITCH_LIMIT_RAD = math.radians(60.0)
CAMERA_HEIGHT_M = 1.2                # R1 Pro head, roughly


def _wrap(a: float) -> float:
    """Fold an angle into (-pi, pi]."""
    return (a + math.pi) % (2 * math.pi) - math.pi


@dataclass
class Viewpoint:
    """(x, y, yaw, pitch) plus the primitives that move it.

    Deliberately dumb: the primitives mutate this and nothing else. They touch no BDDL
    literal, so no expert plan changes except for prepended discovery moves, and the
    17 semantic tools keep their meaning.
    """

    x: float = 0.0
    y: float = 0.0
    yaw: float = 0.0                 # radians, 0 = +x
    pitch: float = 0.0               # radians, + = up
    seen: set = field(default_factory=set)

    # -- primitives ------------------------------------------------------- #
    def turn_left(self) -> None:
        self.yaw = _wrap(self.yaw + TURN_STEP_RAD)

    def turn_right(self) -> None:
        self.yaw = _wrap(self.yaw - TURN_STEP_RAD)

    def move_ahead(self) -> None:
        self._translate(self.yaw)

    # WASD. `move_ahead` + `turn_*` can reach any pose in principle, but not without
    # changing where the camera POINTS, and that is the whole difficulty `detect`
    # measures: an object hidden behind furniture is recovered by stepping sideways
    # while still looking at it. Turning to walk and turning back costs 4 extra calls
    # and loses the framing in between, which is why a policy that can only turn-walk
    # -turn tends not to bother. Measured motivation: 77 of 273 scope objects were
    # `outside_frustum` and 28 occluded from the start pose, both of which are
    # properties of WHERE YOU STAND rather than of where you look.
    def move_back(self) -> None:
        self._translate(self.yaw + math.pi)

    def strafe_left(self) -> None:
        self._translate(self.yaw + math.pi / 2)

    def strafe_right(self) -> None:
        self._translate(self.yaw - math.pi / 2)

    def _translate(self, heading: float) -> None:
        self.x += MOVE_STEP_M * math.cos(heading)
        self.y += MOVE_STEP_M * math.sin(heading)

    def look_up(self) -> None:
        self.pitch = min(self.pitch + PITCH_STEP_RAD, PITCH_LIMIT_RAD)

    def look_down(self) -> None:
        self.pitch = max(self.pitch - PITCH_STEP_RAD, -PITCH_LIMIT_RAD)

    def teleport(self, x: float, y: float, yaw: float | None = None) -> None:
        """Where `go_to` puts the camera: at the object, facing it, pitch reset."""
        self.x, self.y = x, y
        if yaw is not None:
            self.yaw = _wrap(yaw)
        self.pitch = 0.0

    # -- visibility ------------------------------------------------------- #
    def bearing_to(self, pos) -> float:
        return _wrap(math.atan2(pos[1] - self.y, pos[0] - self.x) - self.yaw)

    def range_to(self, pos) -> float:
        return math.hypot(pos[0] - self.x, pos[1] - self.y)

    def elevation_to(self, pos) -> float:
        d = max(self.range_to(pos), 1e-3)
        return math.atan2(pos[2] - CAMERA_HEIGHT_M, d)

    def in_view(self, pos) -> bool:
        """Bearing within the horizontal cone, elevation within the vertical one,
        and inside range. No occlusion: like `semantic_tools._in_fov`, this is an
        FOV+range approximation and is named as one rather than called visibility."""
        if self.range_to(pos) > FOV_RANGE_M:
            return False
        if abs(self.bearing_to(pos)) > FOV_HALF_ANGLE_RAD:
            return False
        return abs(self.elevation_to(pos) - self.pitch) <= FOV_HALF_PITCH_RAD

    # -- reporting -------------------------------------------------------- #
    def describe(self, pos, metric: bool) -> dict:
        """How an in-view object is described back to the policy.

        @metric is `Layout.is_real`. Under a generated layout a distance in metres is
        not a measurement of anything, so it is not reported -- the policy gets an
        ordinal band instead, which is true of the layout either way. Reporting "2.3 m"
        off invented coordinates is exactly the plausible-looking fake the honesty
        rules forbid.
        """
        b = self.bearing_to(pos)
        side = "ahead" if abs(b) < math.radians(15) else (
            "to your left" if b > 0 else "to your right")
        out = {"direction": side}
        r = self.range_to(pos)
        if metric:
            out["distance_m"] = round(r, 2)
        else:
            out["distance"] = "close" if r < 1.5 else ("near" if r < 4.0 else "far")
        if pos[2] > CAMERA_HEIGHT_M + 0.3:
            out["height"] = "above you"
        elif pos[2] < CAMERA_HEIGHT_M - 0.8:
            out["height"] = "low down"
        return out

    def state(self) -> dict:
        """The viewpoint as the policy sees it. Yaw in degrees because the policy
        reasons in text and 45-degree steps are easier to count than 0.785 radians."""
        return {"facing_deg": round(math.degrees(self.yaw)) % 360,
                "pitch_deg": round(math.degrees(self.pitch))}
